mixed-port: 7897
tcp-concurrent: true
mode: rule
ipv6: false
log-level: info
global-client-fingerprint: chrome
find-process-mode: strict
unified-delay: true
profile:
  store-selected: true
  store-fake-ip: true
geodata-mode: true
geox-url:
  geoip: "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/geoip.dat"
  geosite: "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat"
  mmdb: "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/Country.mmdb"
  asn: "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/GeoLite2-ASN.mmdb"
tun:
  enable: true
  stack: system
  dns-hijack:
    - "any:53"
    - "tcp://any:53"
  auto-route: true
  auto-detect-interface: true
dns:
  enable: true
  listen: 0.0.0.0:53
  ipv6: false
  enhanced-mode: fake-ip
  prefer-h3: true
  fake-ip-range: 198.18.0.1/16
  # default-nameserver: [223.5.5.5, 119.29.29.29]
  # direct-nameserver: ['https://doh.pub/dns-query', 'https://dns.alidns.com/dns-query']
  # nameserver: ['https://8.8.8.8/dns-query#Proxies', 'https://1.1.1.1/dns-query#Proxies']
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  fallback:
    - https://1.1.1.1/dns-query
    - https://8.8.8.8/dns-query
  fallback-filter:
    geoip: true
    geoip-code: CN
    ip-cidr:
      - 240.0.0.0/4
      - 0.0.0.0/8
      - 127.0.0.0/8
      - 10.0.0.0/8
      - 172.16.0.0/12
      - 192.168.0.0/16
  nameserver-policy:
    "geosite:cn":
      - https://dns.alidns.com/dns-query
    "geosite:geolocation-!cn":
      - https://8.8.8.8/dns-query
sniffer:
  enable: true
  sniff:
    TLS:
      ports: [443, 8443]
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true

proxy-groups:
  - icon: https://raw.githubusercontent.com/Semporia/Hand-Painted-icon/master/Universal/Auto_Speed.png
    include-all: true
    exclude-filter: (?i)GB|Traffic|Expire|Premium|频道|订阅|ISP|流量|到期|重置
    name: Proxies
    type: select

  - icon: https://raw.githubusercontent.com/Semporia/Hand-Painted-icon/master/Social_Media/Telegram.png
    name: Telegram
    type: select
    include-all: true

  - icon: https://raw.githubusercontent.com/tugepaopao/Image-Storage/master/cartoon/Cute/%23.png
    name: AI
    type: select
    include-all: true

  - icon: https://raw.githubusercontent.com/Semporia/Hand-Painted-icon/master/Social_Media/FilmAffinity.png
    name: Emby
    type: select
    include-all: true

  - icon: https://github.com/Orz-3/face/raw/master/Scholar.png
    name: Crypto
    type: select
    include-all: true

# 规则提供者
rule-providers:
  telegram:
    url: https://raw.githubusercontent.com/Repcz/Tool/X/Clash/Rules/Telegram.list
    path: ./ruleset/telegram.list
    behavior: classical
    interval: 86400
    format: text
    type: http

  ai:
    url: https://rule.kelee.one/Clash/OpenAI.yaml
    path: ./ruleset/ai.list
    behavior: classical
    interval: 86400
    format: yaml
    type: http

  emby:
    url: https://whatshub.top/rule/Emby.list
    path: ./ruleset/emby.list
    behavior: classical
    interval: 86400
    format: text
    type: http

  crypto:
    url: https://github.com/blackmatrix7/ios_rule_script/raw/master/rule/Clash/Crypto/Crypto.list
    path: ./ruleset/crypto.list
    behavior: classical
    interval: 86400
    format: text
    type: http

  ChinaIP:
    url: https://github.com/Repcz/Tool/raw/X/Clash/Rules/ChinaIP.list
    path: ./ruleset/ChinaIP.list
    behavior: classical
    interval: 86400
    format: text
    type: http

# 规则集
rules:
  - RULE-SET,telegram,Telegram
  - RULE-SET,ai,AI
  - RULE-SET,emby,Emby
  - RULE-SET,crypto,Crypto
  - RULE-SET,ChinaIP,DIRECT
  - GEOSITE,spotify,Proxies
  - GEOSITE,github,Proxies
  - GEOSITE,microsoft,DIRECT
  - GEOSITE,gfw,Proxies
  - GEOIP,lan,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,Proxies
